spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        jdbc: debug
      #JPA log
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    #MyBatis
    hello:
      itemservice:
        repository:
          mybatis: trace

#MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true